environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu
  RUST_BACKTRACE: full
  PYTHON: "C:\\Python36"
  PYTHON_VERSION: "3.6.x"
  PYTHON_ARCH: "64"
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV
  - python -m pip install pytest
  - python --version
build: false
test_script:
  - ps: cd core
  - cargo build
  - cargo test
  - python -m pytest -v ..
