dist: xenial
language: rust
rust:
  - stable
  - beta
os:
  - linux
  - osx
env:
  global:
    - RUST_BACKTRACE=1

addons:
  apt:
    packages: libgtk-3-dev
  homebrew:
    packages: gtk+3

cache: cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
