language: rust
dist: trusty
sudo: required
osx_image: xcode8.3

rust:
  - stable
  - beta

os:
  - linux
  - osx

cache: cargo

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6-venv

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install python3; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then python3 -m venv .venv; else pyvenv-3.6 .venv; fi
  - source .venv/bin/activate
  - pip install pytest
  - pytest --version

script:
  - cd $TRAVIS_BUILD_DIR/core
  - cargo build
  - cargo test
  - cd $TRAVIS_BUILD_DIR
  - pytest -v
