[package]
name = "ced-gui"
version = "0.1.0"
authors = ["Martin Chaine <martin@casimir.me>"]
edition = "2018"

[dependencies]
ced-remote = { path = "../remote" }
env_logger = "0.6"
gdk = "0.9"
gio = "0.5"
glib = "0.6"
gtk = { version = "0.5", features = ["v3_16"] }
log = "0.4"