[package]
name = "ced"
version = "0.1.0"
authors = ["Martin Chaine <martin@casimir.me>"]

[lib]
name = "ced"
path = "src/lib.rs"

[[bin]]
name = "ced"
path = "src/main.rs"

[dependencies]
cfg-if = "0.1"
clap = "2.31"
crossbeam-channel = "0.2"
env_logger = "0.5"
failure = "0.1"
failure_derive = "0.1"
human-panic = "1.0"
ignore = "0.4"
lazy_static = "1.0"
log = "0.4"
mio = "0.6"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[target.'cfg(unix)'.dependencies]
mio-uds = "0.6"
termion = "1.5"

[target.'cfg(windows)'.dependencies]
mio-named-pipes = "0.1"
winapi = "0.3"

[dev-dependencies]
itertools = "0.7"
