[package]
name = "ced"
version = "0.1.0"
authors = ["Martin Chaine <martin@casimir.me>"]
edition = "2018"
default-run = "ced"

[lib]
name = "ced"
path = "src/lib.rs"

[features]
default = ["term"]

term = ["termion"]

[dependencies]
ced-remote = { path = "../remote" }
clap = "2.33"
crossbeam-channel = "0.3"
dirs = "1.0"
env_logger = "0.6"
ignore = "0.4"
log = "0.4"
mio = "0.6"
ornament = "0.2"
rbtset = "1.0"
regex = "1.2"
rlua = "0.16"

[target.'cfg(unix)'.dependencies]
termion = { version = "1.5", optional = true }

[dev-dependencies]
itertools = "0.8"