[package]
name = "ced"
version = "0.1.0"
authors = ["Martin Chaine <martin@casimir.me>"]

[dependencies]
clap = "2.31"
jsonrpc-lite = "0.5"
mio = "0.6"
mio-uds = "0.6"
quick-error = "1.2"
serde_json = "1.0"