[package]
name = "ced"
version = "0.1.0"
authors = ["Martin Chaine <martin@casimir.me>"]

[lib]
name = "ced"
path = "src/lib.rs"

[[bin]]
name = "ced"
path = "src/main.rs"

[dependencies]
ced-remote = { path = "../remote" }
clap = "2.31"
crossbeam-channel = "0.2"
env_logger = "0.5"
failure = "0.1"
failure_derive = "0.1"
human-panic = "1.0"
ignore = "0.4"
lazy_static = "1.0"
log = "0.4"
mio = "0.6"
regex = "1.0"

[target.'cfg(unix)'.dependencies]
termion = "1.5"

[dev-dependencies]
itertools = "0.7"
