[package]
name = "ced"
version = "0.1.0"
authors = ["Martin Chaine <martin@casimir.me>"]

[dependencies]
clap = "2.31"
env_logger = "0.5"
jsonrpc-lite = "0.5"
lazy_static = "1.0"
log = "0.4"
mio = "0.6"
quick-error = "1.2"
regex = "1.0"
serde_json = "1.0"

[target.'cfg(unix)'.dependencies]
futures = "0.1"
ignore = "0.4"
mio-uds = "0.6"
termion = "1.5"
tokio = "0.1"
tokio-core = "0.1"
tokio-uds = "0.2"

[target.'cfg(windows)'.dependencies]
mio-named-pipes = "0.1"
winapi = "0.3"
